### ISSUE TITLE
Error installing Appium-interceptor-plugin through commandline

### ISSUE THREAD

**Issue by LoveSoni** [AppiumTestDistribution/appium-interceptor-plugin#11]
**Command used to install plugin**: appium plugin install --source=npm appium-interceptor-plugin 
**Machine** Apple Macbook(Intel i9)
**Output**
Error: npm command 'info appium-interceptor-plugin peerDependencies dependencies --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": "E404",
    "summary": "Not Found - GET https://registry.npmjs.org/appium-interceptor-plugin - Not found",
    "detail": "\n 'appium-interceptor-plugin@*' is not in this registry.\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}

STDERR:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/appium-interceptor-plugin - Not found
npm ERR! 404 
npm ERR! 404  'appium-interceptor-plugin@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/{username}/.npm/_logs/2024-01-08T09_54_15_622Z-debug-0.log

It looks like plugin is not available on global registry

**Comment by sudharsan-selvaraj** [comment]
There was a typo in the readme. The correct plugin name is `appium-interceptor`. Running the below command should fix the installation.
`appium plugin install --source=npm appium-interceptor`
