### ISSUE TITLE
appium-interceptor test connection script got failed

### ISSUE THREAD

**Issue by LoveSoni** [AppiumTestDistribution/appium-interceptor-plugin#14]
**Prerequisites:**
Appium Version: 2.4.1
Npm Version: 10.2.4
Apple Macbook Intel(i9)
**Steps to Reproduce**
a) Install appium inspector plugin
`appium plugin install --source=npm appium-interceptor`
<img width="567" alt="Screenshot 2024-01-08 at 18 59 30" src="https://github.com/AppiumTestDistribution/appium-interceptor-plugin/assets/33176624/9ad3c2cf-d24d-4804-8c07-c3048d74c1c9">
b) Now download ca certificate from [here](https://github.com/AppiumTestDistribution/appium-interceptor-plugin/blob/master/certificate/certs/ca.pem) and install it on device
<img width="341" alt="Screenshot 2024-01-08 at 19 01 20" src="https://github.com/AppiumTestDistribution/appium-interceptor-plugin/assets/33176624/55334eb5-8413-447b-9528-8dd62079f959">
Note: Make sure certificate is trusted
c) Now test the connection with following command
`appium plugin run appium-interceptor test-connection`
<img width="564" alt="Screenshot 2024-01-08 at 19 02 43" src="https://github.com/AppiumTestDistribution/appium-interceptor-plugin/assets/33176624/034f5630-e5d1-40d1-ae9d-d83f9ea0cfbc">
d) Observe that test connection script is getting failed

**Comment by LoveSoni** [comment]
oh ok, i was trying to run my test with the following desired capabilities
`  capabilities.setCapability("appium:platformName", "android");
        capabilities.setCapability("appium:app","/.//test_app_mitm_proxy.apk");
        capabilities.setCapability("appium:forceAppLaunch", true);
        capabilities.setCapability("appium:automationName","uiautomator2");
        capabilities.setCapability("appium:intercept", true);`

but getting following error on appium server
Encountered internal error running command: Error: ENOENT: no such file or directory, lstat '/Users/{username}/node_modules/appium-interceptor/certificate'

**Comment by saikrishna321** [comment]
@LoveSoni I have published latest version beta.4 

Can you try with that version and let us know.

**Comment by LoveSoni** [comment]
Hi @sudharsan-selvaraj  I've tried mocking feature using appium java
` DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("appium:platformName", "android");
        capabilities.setCapability("appium:app","./test_app_mitm_proxy.apk");
        capabilities.setCapability("appium:forceAppLaunch", true);
        capabilities.setCapability("noReset", true);
        capabilities.setCapability("fullReset", false);
        capabilities.setCapability("appium:automationName","uiautomator2");
        capabilities.setCapability("appium:intercept", true);
        AppiumDriver appiumDriver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
        File file = new File("./apis/mock.json");
        InputStream is = new FileInputStream(file);
        String jsonTxt = IOUtils.toString(is, "UTF-8");
        JSONParser parser = new JSONParser();
        JSONObject json = (JSONObject) parser.parse(jsonTxt);
        appiumDriver.execute("interceptor: addMock", json);
        appiumDriver.findElement(By.xpath("//android.widget.TextView[@text='Get User List']")).click();

But getting following exception 
`Exception in thread "main" org.openqa.selenium.UnsupportedCommandException: interceptor: addMock
Build info: version: '4.16.1', revision: '9b4c83354e'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '14.2.1', java.version: '11.0.16'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [2f24c946-667b-46a7-9ec4-0f50525c74dd, interceptor: addMock {"config":{"responseBody":{"per_page":6,"total":12,"data":[{"last_name":"Bluth","id":1,"avatar":"https:\/\/reqres.in\/img\/faces\/1-image.jpg","first_name":"George","email":"test.bluth@reqres.in"},{"last_name":"Weaver","id":2,"avatar":"https:\/\/reqres.in\/img\/faces\/2-image.jpg","first_name":"Janet","email":"janet.weaver@reqres.in"}],"page":1,"total_pages":2,"support":{"text":"To keep ReqRes free, contributions towards server costs are appreciated!","url":"https:\/\/reqres.in\/#support-heading"}},"url":"\/api\/users?.*"}}]
Capabilities {appium:app: /Users/user/Downloads/test_..., appium:appPackage: com.workshop.testapp, appium:automationName: uiautomator2, appium:databaseEnabled: false, appium:desired: {app: /Users/user/Downloads/test_..., automationName: uiautomator2, forceAppLaunch: true, fullReset: false, intercept: true, noReset: true, platformName: ANDROID}, appium:deviceApiLevel: 34, appium:deviceManufacturer: Google, appium:deviceModel: sdk_gphone64_x86_64, appium:deviceName: emulator-5554, appium:deviceScreenDensity: 560, appium:deviceScreenSize: 1440x3120, appium:deviceUDID: emulator-5554, appium:forceAppLaunch: true, appium:fullReset: false, appium:intercept: true, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:noReset: true, appium:pixelRatio: 3.5, appium:platformVersion: 14, appium:statBarHeight: 144, appium:takesScreenshot: true, appium:viewportRect: {height: 2748, left: 0, top: 144, width: 1440}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 2f24c946-667b-46a7-9ec4-0f50525c74dd
`
    `

**Comment by saikrishna321** [comment]
@LoveSoni Please share full server logs.

**Comment by LoveSoni** [comment]
[appium-server-logs.txt](https://github.com/AppiumTestDistribution/appium-interceptor-plugin/files/13889617/appium-server-logs.txt)

**Comment by sudharsan-selvaraj** [comment]
The command name should be `interceptor: addMock`. There is whitespace after `interceptor:` keyword.

**Comment by LoveSoni** [comment]
Thanks @sudharsan-selvaraj, but now when i'm running the script, getting following certificate error on appium server
And then the internet stopped working on android device

```
}
HTTPS_CLIENT_ERROR
[Error: 800B8E5DF87F0000:error:0A000416:SSL routines:ssl3_read_bytes:ssl/tls alert certificate unknown:ssl/record/rec_layer_s3.c:861:SSL alert number 46
] {
  library: 'SSL routines',
  reason: 'ssl/tls alert certificate unknown',
  code: 'ERR_SSL_SSL/TLS_ALERT_CERTIFICATE_UNKNOWN'
}
```

**Comment by sudharsan-selvaraj** [comment]
I could be a certificate issue. Trying uninstalling the previous certificate and follow the steps from https://github.com/AppiumTestDistribution/appium-interceptor-plugin/blob/master/docs/certificate-installation.md and give another try.

**Comment by LoveSoni** [comment]
Thanks,  it is working fine
