### ISSUE TITLE
Error: Android 14 CA certifcate installed testing connection fails

### ISSUE THREAD

**Issue by ygarg465** [AppiumTestDistribution/appium-interceptor-plugin#29]
**Describe the issue**
After manually copying and installing CA certificate on Android Emulator. And running this command `appium plugin run appium-interceptor test-connection`.
I am getting 
![image](https://github.com/AppiumTestDistribution/appium-interceptor-plugin/assets/80275789/dee4a987-9548-4cd7-bf84-d65a6f69a0f1)
but on the emulator I am getting this
<img src="https://github.com/AppiumTestDistribution/appium-interceptor-plugin/assets/80275789/63e536dc-6981-4671-a3b2-adb1541226c7" height="250"/>

How do we solve this ?

**Device Information**
OS: Android
Version: API 34 (Android 14)
Device: Pixel 7 Pro

**Comment by sudharsan-selvaraj** [comment]
@ygarg465 Looks like the setup is working on the device. The errors that you are getting on the console are expected and you can ignore them.

**Comment by ygarg465** [comment]
> @ygarg465 Looks like the setup is working on the device. The errors that you are getting on the console are expected and you can ignore them.

This means that this is not the reason for failing to intercept the requests in tests.

Then I should file another issue for that.

**Comment by sudharsan-selvaraj** [comment]
@ygarg465 If there is any issue with intercepting, please do share the code you are using and any logs that can help us debug the issue.
