### ISSUE TITLE
Error(Android): Invalid agrument:  Did not receive an appropriate execute method parameters object. It needs to be deserializable as a plain JS object

### ISSUE THREAD

**Issue by ygarg465** [AppiumTestDistribution/appium-interceptor-plugin#30]
**Describe the issue**
Mocking request using below code
```js
await driver.execute("interceptor: addMock", [
      {
        config: {
          url: "https://domain/sms/sendOTP",
          method: "POST",
          responseBody: JSON.stringify({
            success: true,
            message: "OTP sent successfully",
          }),
        },
      },
    ]);
```
results in this error on Appium server logs
`invalid argument: Did not receive an appropriate execute method parameters object. It needs to be deserializable as a plain JS object`

This also happens if we pass an empty object or the example code in the commands sections
```js
 const authorizationMock = await driver.execute("interceptor: addMock", [{
    config: {
        url: "**/reqres.in/**",
        headers: {
            "Authorization" : "Bearer bearertoken"
        }
    }
 }]);
```
**Device Information**
OS: Android
Version: API 34 (Android 14)
Device: Pixel 7 Pro

**Comment by ygarg465** [comment]
Hey @sudharsan-selvaraj, did you look at this issue?
Because it's a blocker for me to move forward.

**Comment by sudharsan-selvaraj** [comment]
@ygarg465 Are you using webdriver.io on the client side?

**Comment by ygarg465** [comment]
@sudharsan-selvaraj Actually yes

**Comment by sudharsan-selvaraj** [comment]
Could you please try with the below syntax?

```
await driver.execute("interceptor: addMock",  {
        config: {
          url: "https://domain/sms/sendOTP",
          method: "POST",
          responseBody: JSON.stringify({
            success: true,
            message: "OTP sent successfully",
          }),
        },
      });
```

**Comment by ygarg465** [comment]
@sudharsan-selvaraj Yes this syntax resolves the above issue. Was this due to WebDriver ? If Yes we can update the docs to add this usecase as well.

However now I am getting this error in logcat when the request is sent from the app.

 `[ERROR:ssl_client_socket_impl.cc(970)] handshake failed; returned -1, SSL error code 1, net_error -202`

**Comment by ygarg465** [comment]
@sudharsan-selvaraj Addtional context
It's a hybrid application developed using CapacitorJS

**Comment by ygarg465** [comment]
I should create a separate issue for that.
