### ISSUE TITLE
How to enable this plugin to test the app using Headspin devices

### ISSUE THREAD

**Issue by PrakashBalraj94** [AppiumTestDistribution/appium-interceptor-plugin#55]
Hi @saikrishna321 / @sudharsan-selvaraj , 

Im performing mobile app testing using Headspin devices, could you please help me with the steps to be followed to perform network interception in Headspin devices. 

I have tried adding "headspin:appiumPlugins: ['appium-interceptor']" capability but received "invalid plugin error" while executing the script.

Kindly help me in resolving the above issue. Thank you!

Regards,
Prakash Balraj

**Comment by saikrishna321** [comment]
@PrakashBalraj94 you need to contact headspin support
